dirty patch to show alternative keyword names
Better imo, as this allows the keyword to be enforced, and doesn't have a corner case just to allow wireguard to work

diff --git a/executor-scripts/linux/link b/executor-scripts/linux/link
--- a/executor-scripts/linux/link
+++ b/executor-scripts/linux/link
@@ -67,13 +67,18 @@ create)
 
 		${MOCK} ip link add link "$IF_VLAN_RAW_DEVICE" name "$IFACE" type vlan id "$IF_VLAN_ID"
 
-	# Only fetch physical devices from the configured network namespace
-	elif [ -n "$IF_NETNS" ] && ${MOCK} ip netns exec "$IF_NETNS" [ -d /sys/class/net/"$IFACE"/device ]; then
+	elif [ -n "$IF_ORIGIN_NETNS" ]; then
+		# NOTE: Early negation is important so this condition is ignored during tests
+		if ! ${MOCK} ip netns exec "$IF_ORIGIN_NETNS" [ -d /sys/class/net/"$IFACE" ]; then
+			printf 'Interface %s is missing from network namespace %s\n' "$IFACE" "$IF_ORIGIN_NETNS"
+			exit 1
+		fi
+
 		# NOTE: Negate test to treat wired interfaces as the default case during tests
-		if ! phy=$(${MOCK} ip netns exec "$IF_NETNS" cat /sys/class/net/"$IFACE"/phy80211/name 2> /dev/null); then
-			${MOCK} ip -n "$IF_NETNS" link set "$IFACE" netns $$
+		if ! phy=$(${MOCK} ip netns exec "$IF_ORIGIN_NETNS" cat /sys/class/net/"$IFACE"/phy80211/name 2> /dev/null); then
+			${MOCK} ip -n "$IF_ORIGIN_NETNS" link set "$IFACE" netns $$
 		else
-			${MOCK} ip netns exec "$IF_NETNS" "$(command -v iw)" phy "$phy" set netns $$
+			${MOCK} ip netns exec "$IF_ORIGIN_NETNS" "$(command -v iw)" phy "$phy" set netns $$
 		fi
 
 	fi
@@ -102,13 +107,12 @@ destroy)
 	if [ "$IF_LINK_TYPE" = 'dummy' ] || [ "$IF_LINK_TYPE" = 'veth' ] || is_vlan; then
 		${MOCK} ip link del "$IFACE"
 
-	# Only send physical devices to the configured network namespace
-	elif [ -n "$IF_NETNS" ] && [ -d /sys/class/net/"$IFACE"/device ]; then
+	elif [ -n "$IF_ORIGIN_NETNS" ]; then
 		# NOTE: Negate test to treat wired interfaces as the default case during tests
 		if ! phy=$(${MOCK} cat /sys/class/net/"$IFACE"/phy80211/name 2> /dev/null); then
-			${MOCK} ip link set "$IFACE" netns "$IF_NETNS"
+			${MOCK} ip link set "$IFACE" netns "$IF_ORIGIN_NETNS"
 		else
-			${MOCK} iw phy "$phy" set netns name "$IF_NETNS"
+			${MOCK} iw phy "$phy" set netns name "$IF_ORIGIN_NETNS"
 		fi
 	fi
 	;;
